#! /bin/sh
### BEGIN INIT INFO
# Provides:          preserve
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0
# Short-Description: Preserve files of the VM
# Description:
### END INIT INFO

NETDOWN=yes

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

do_stop () {
 	mount
	if [ -f /etc/default/preserve ]; then
           mkdir -p /hostlab/$(uname -n)/preserve
	   (tar cfT - /etc/default/preserve | tar xCf /hostlab/$(uname -n)/preserve - ) > /dev/null 2>&1
	fi
}

case "$1" in
  start)
	# No-op
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac

:
