#! /bin/sh
### BEGIN INIT INFO
# Provides:          pipsecd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/pipsecd

FLAGS="defaults 50"

test -f $DAEMON || exit 0

case "$1" in
  start)
    start-stop-daemon --start --verbose --exec $DAEMON
    ;;
  stop)
    start-stop-daemon --stop --verbose --exec $DAEMON
    ;;
  restart|force-reload) 
    start-stop-daemon --stop --verbose --exec $DAEMON
    sleep 5
    start-stop-daemon --start --verbose --exec $DAEMON
    ;;
  reload)
    killall -HUP $DAEMON
    ;;
  *)
    echo "Usage: /etc/init.d/pipsecd {start|stop|restart|reload|force-reload}"
    exit 1
    ;;
esac

exit 0
