#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          smcroute
# Required-Start:    $syslog $local_fs $network
# Required-Stop:     $syslog $local_fs $network
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Static multicast router daemon
# Description:       SMCRoute is a tool to manipulate the multicast routes
#                    of the Linux kernel. It can be used as an alternative
#                    to dynamic multicast routers like mrouted in situation
#                    where static multicast routes should be maintained
#                    and/or no proper IGMP signaling exists.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/smcroute
DAEMON_OPTS=-d
NAME=smcroute
DESC="static multicast router daemon"

test -x $DAEMON || exit 0

# Include smcroute defaults if available
if [ -f /etc/default/smcroute ] ; then
	. /etc/default/smcroute
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet \
		--exec $DAEMON -- $DAEMON_OPTS
	if [ -x /etc/smcroute/startup.sh ]; then
		/etc/smcroute/startup.sh
	fi
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	$DAEMON -k || true
	echo "$NAME."
	;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	$DAEMON -k || true
	sleep 1
	start-stop-daemon --start --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
	if [ -x /etc/smcroute/startup.sh ]; then
		/etc/smcroute/startup.sh
	fi
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
